### ISSUE TITLE
How should I do to append the openaikey into this app ? I am new to Cmake and Qt. thanks

### ISSUE THREAD

**Issue by zx377262372** [sucv/HoloLive2dChatbot#2]

**Comment by zx377262372** [comment]
Also Azure is too.

**Comment by zx377262372** [comment]
Thank you most sincerely

**Comment by zx377262372** [comment]
Everytime I talk to it，it was crashed

**Comment by sucv** [comment]
Thanks for your interest in this humble app.
Please follow the tutorial https://www.alphr.com/set-environment-variables-windows-11/ to add the Key. After which, the app should be able to load them.

There are three keys to add.

1. OPENAI_API_KEY
2. SPEECH_KEY
3. SPEECH_REGION

1 can be found in your OpenAI account, 2 and 3 can be found in your Azure account.

**Comment by zx377262372** [comment]
> Thanks for your interest in this humble app. Please follow the tutorial https://www.alphr.com/set-environment-variables-windows-11/ to add the Key. After which, the app should be able to load them.
> 
> There are three keys to add.
> 
> 1. OPENAI_API_KEY
> 2. SPEECH_KEY
> 3. SPEECH_REGION
> 
> 1 can be found in your OpenAI account, 2 and 3 can be found in your Azure account.

thanks indeed
